spring.application.name=demo

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/srtpv_customer?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rkr@72485
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#logging

#directory (it will automatically generate a file named 'spring.log')
logging.file.path=logs/solarNetBilling.log

# Custom format for the console output
#logging.pattern.console=%d{dd-MM-yyyy |-| HH:mm:ss} %-5level [%thread]  %logger{36} - %msg%n

# Custom format for the generated log file
#logging.pattern.file=%d{dd-MM-yyyy |-| HH:mm:ss} %-5level [%thread]  %logger{36} - %msg%n
