spring.application.name=demo

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/srtpv_customer?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rkr@72485
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
